---
- hosts: internet_pi
  become: true

  pre_tasks:
    - name: Load configuration
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yaml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yaml

  tasks:
    - name: Setup Docker
      ansible.builtin.import_tasks: tasks/docker.yaml

    - name: Setup Internet Monitoring
      ansible.builtin.import_tasks: tasks/internet-monitoring.yaml
      when: monitoring_enable
